### ISSUE TITLE
s3s-fs server giving error The AWS Access Key Id you provided does not exist in our records

### ISSUE THREAD

**Issue by joestein** [Nugine/s3s#124] opened 2024-01-11 21:41 UTC
I am not sure what is wrong, I have my client setup

```
s3 = boto3.client('s3', aws_access_key_id="asdf", aws_secret_access_key="asdf", endpoint_url='http://localhost:8014')
```
I also have the creds in my ~/.aws/credentias
```
[default]
aws_access_key_id=asdf
aws_secret_access_key=asdf
```
and even exported the env vars

and starting the server
```
target/debug/s3s-fs --access-key asdf --secret-key asdf ~/dev/s3
```

And getting the error

```
ERROR:root:An error occurred (InvalidAccessKeyId) when calling the CreateBucket operation: The AWS Access Key Id you provided does not exist in our records.
{'ResponseMetadata': {'HTTPStatusCode': 200, 'HTTPHeaders': {'content-type': 'application/xml', 'content-length': '193', 'date': 'Thu, 11 Jan 2024 21:36:22 GMT'}, 'RetryAttempts': 0}, 'Buckets': [{'Name': 'test', 'CreationDate': datetime.datetime(2024, 1, 11, 20, 40, 5, 24000, tzinfo=tzutc())}]}
```

Any idea what I am doing wrong?

**Comment by cameronelliott** [comment] 2024-01-16 06:51
@joestein 

Have you tried using the start script:
`$ ./scripts/s3s-fs.sh`

I'm also attaching my ~/.aws/credentials file
[credentials.txt](https://github.com/Nugine/s3s/files/13946342/credentials.txt)

EXCEPT! you must rename it from credentials.txt -> credentials

When I used the start script and this credentials file, everything worked as expected.
With the key/secet as follows:
```
[default]
aws_access_key_id = AKEXAMPLES3S
aws_secret_access_key = SKEXAMPLES3S
```

**Comment by Nugine** [comment] 2024-01-16 08:36
I cannot reproduce the error. Could you provide debug logs?
```bash
export RUST_LOG="s3s_fs=debug,s3s=debug"
```
You can also try to modify [the example start script](https://github.com/Nugine/s3s/blob/main/scripts/s3s-fs.sh).

**Comment by Nugine** [comment] 2024-03-07 11:37
Closing as stalled. Feel free to reopen if you have new information.

**Closed by Nugine** 2024-03-07 11:37 UTC
Labels: needs-repro
